# Generated by Django 6.0.1 on 2026-02-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='Порядок сортировки'),
        ),
    ]
